//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonsterHunterWorld.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonsterHunterWorld.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arm {
            get {
                object obj = ResourceManager.GetObject("arm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap armorset_empty {
            get {
                object obj = ResourceManager.GetObject("armorset_empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chest {
            get {
                object obj = ResourceManager.GetObject("chest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap head {
            get {
                object obj = ResourceManager.GetObject("head", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_ammo.svg.
        /// </summary>
        internal static string item_ammo {
            get {
                return ResourceManager.GetString("item_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_bait.svg.
        /// </summary>
        internal static string item_bait {
            get {
                return ResourceManager.GetString("item_bait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_barrel.svg.
        /// </summary>
        internal static string item_barrel {
            get {
                return ResourceManager.GetString("item_barrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_barrelbomb.svg.
        /// </summary>
        internal static string item_barrelbomb {
            get {
                return ResourceManager.GetString("item_barrelbomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_binoculars.svg.
        /// </summary>
        internal static string item_binoculars {
            get {
                return ResourceManager.GetString("item_binoculars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_body.svg.
        /// </summary>
        internal static string item_body {
            get {
                return ResourceManager.GetString("item_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_bone.svg.
        /// </summary>
        internal static string item_bone {
            get {
                return ResourceManager.GetString("item_bone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_book.svg.
        /// </summary>
        internal static string item_book {
            get {
                return ResourceManager.GetString("item_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_boomerang.svg.
        /// </summary>
        internal static string item_boomerang {
            get {
                return ResourceManager.GetString("item_boomerang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_bottle.svg.
        /// </summary>
        internal static string item_bottle {
            get {
                return ResourceManager.GetString("item_bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_bug.svg.
        /// </summary>
        internal static string item_bug {
            get {
                return ResourceManager.GetString("item_bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_carapace.svg.
        /// </summary>
        internal static string item_carapace {
            get {
                return ResourceManager.GetString("item_carapace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_charm.svg.
        /// </summary>
        internal static string item_charm {
            get {
                return ResourceManager.GetString("item_charm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_charmore.svg.
        /// </summary>
        internal static string item_charmore {
            get {
                return ResourceManager.GetString("item_charmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_coin.svg.
        /// </summary>
        internal static string item_coin {
            get {
                return ResourceManager.GetString("item_coin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_dung.svg.
        /// </summary>
        internal static string item_dung {
            get {
                return ResourceManager.GetString("item_dung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_emptybottle.svg.
        /// </summary>
        internal static string item_emptybottle {
            get {
                return ResourceManager.GetString("item_emptybottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_fang.svg.
        /// </summary>
        internal static string item_fang {
            get {
                return ResourceManager.GetString("item_fang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_feystone.svg.
        /// </summary>
        internal static string item_feystone {
            get {
                return ResourceManager.GetString("item_feystone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_gem.svg.
        /// </summary>
        internal static string item_gem {
            get {
                return ResourceManager.GetString("item_gem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_herb.svg.
        /// </summary>
        internal static string item_herb {
            get {
                return ResourceManager.GetString("item_herb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_hide.svg.
        /// </summary>
        internal static string item_hide {
            get {
                return ResourceManager.GetString("item_hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_husk.svg.
        /// </summary>
        internal static string item_husk {
            get {
                return ResourceManager.GetString("item_husk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_monster_jaw.svg.
        /// </summary>
        internal static string item_jaw {
            get {
                return ResourceManager.GetString("item_jaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_knife.svg.
        /// </summary>
        internal static string item_knife {
            get {
                return ResourceManager.GetString("item_knife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_liquid.svg.
        /// </summary>
        internal static string item_liquid {
            get {
                return ResourceManager.GetString("item_liquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_meat.svg.
        /// </summary>
        internal static string item_meat {
            get {
                return ResourceManager.GetString("item_meat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_monsterjaw.svg.
        /// </summary>
        internal static string item_monsterjaw {
            get {
                return ResourceManager.GetString("item_monsterjaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_mushroom.svg.
        /// </summary>
        internal static string item_mushroom {
            get {
                return ResourceManager.GetString("item_mushroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_ore.svg.
        /// </summary>
        internal static string item_ore {
            get {
                return ResourceManager.GetString("item_ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_pellets.svg.
        /// </summary>
        internal static string item_pellets {
            get {
                return ResourceManager.GetString("item_pellets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_plate.svg.
        /// </summary>
        internal static string item_plate {
            get {
                return ResourceManager.GetString("item_plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_question_mark.svg.
        /// </summary>
        internal static string item_question {
            get {
                return ResourceManager.GetString("item_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_sac.svg.
        /// </summary>
        internal static string item_sac {
            get {
                return ResourceManager.GetString("item_sac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_scale.svg.
        /// </summary>
        internal static string item_scale {
            get {
                return ResourceManager.GetString("item_scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_seed.svg.
        /// </summary>
        internal static string item_seed {
            get {
                return ResourceManager.GetString("item_seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_slinger.svg.
        /// </summary>
        internal static string item_slinger {
            get {
                return ResourceManager.GetString("item_slinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_smoke.svg.
        /// </summary>
        internal static string item_smoke {
            get {
                return ResourceManager.GetString("item_smoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_sphere.svg.
        /// </summary>
        internal static string item_sphere {
            get {
                return ResourceManager.GetString("item_sphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_streamstone.svg.
        /// </summary>
        internal static string item_streamstone {
            get {
                return ResourceManager.GetString("item_streamstone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_tail.svg.
        /// </summary>
        internal static string item_tail {
            get {
                return ResourceManager.GetString("item_tail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_trap.svg.
        /// </summary>
        internal static string item_trap {
            get {
                return ResourceManager.GetString("item_trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_traptool.svg.
        /// </summary>
        internal static string item_traptool {
            get {
                return ResourceManager.GetString("item_traptool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_voucher.svg.
        /// </summary>
        internal static string item_voucher {
            get {
                return ResourceManager.GetString("item_voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_web.svg.
        /// </summary>
        internal static string item_web {
            get {
                return ResourceManager.GetString("item_web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_honey.svg.
        /// </summary>
        internal static string item_webbing {
            get {
                return ResourceManager.GetString("item_webbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_wing.svg.
        /// </summary>
        internal static string item_wing {
            get {
                return ResourceManager.GetString("item_wing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap leg {
            get {
                object obj = ResourceManager.GetObject("leg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_17 {
            get {
                object obj = ResourceManager.GetObject("Monster_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_18 {
            get {
                object obj = ResourceManager.GetObject("Monster_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_19 {
            get {
                object obj = ResourceManager.GetObject("Monster_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_20 {
            get {
                object obj = ResourceManager.GetObject("Monster_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_21 {
            get {
                object obj = ResourceManager.GetObject("Monster_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_22 {
            get {
                object obj = ResourceManager.GetObject("Monster_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_23 {
            get {
                object obj = ResourceManager.GetObject("Monster_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_24 {
            get {
                object obj = ResourceManager.GetObject("Monster_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_25 {
            get {
                object obj = ResourceManager.GetObject("Monster_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_26 {
            get {
                object obj = ResourceManager.GetObject("Monster_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_27 {
            get {
                object obj = ResourceManager.GetObject("Monster_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_28 {
            get {
                object obj = ResourceManager.GetObject("Monster_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_29 {
            get {
                object obj = ResourceManager.GetObject("Monster_29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_30 {
            get {
                object obj = ResourceManager.GetObject("Monster_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_31 {
            get {
                object obj = ResourceManager.GetObject("Monster_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_32 {
            get {
                object obj = ResourceManager.GetObject("Monster_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_33 {
            get {
                object obj = ResourceManager.GetObject("Monster_33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_34 {
            get {
                object obj = ResourceManager.GetObject("Monster_34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_35 {
            get {
                object obj = ResourceManager.GetObject("Monster_35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_36 {
            get {
                object obj = ResourceManager.GetObject("Monster_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_37 {
            get {
                object obj = ResourceManager.GetObject("Monster_37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_38 {
            get {
                object obj = ResourceManager.GetObject("Monster_38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_39 {
            get {
                object obj = ResourceManager.GetObject("Monster_39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_40 {
            get {
                object obj = ResourceManager.GetObject("Monster_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_41 {
            get {
                object obj = ResourceManager.GetObject("Monster_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_42 {
            get {
                object obj = ResourceManager.GetObject("Monster_42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_43 {
            get {
                object obj = ResourceManager.GetObject("Monster_43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_44 {
            get {
                object obj = ResourceManager.GetObject("Monster_44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_45 {
            get {
                object obj = ResourceManager.GetObject("Monster_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_46 {
            get {
                object obj = ResourceManager.GetObject("Monster_46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_47 {
            get {
                object obj = ResourceManager.GetObject("Monster_47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_48 {
            get {
                object obj = ResourceManager.GetObject("Monster_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_49 {
            get {
                object obj = ResourceManager.GetObject("Monster_49", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_50 {
            get {
                object obj = ResourceManager.GetObject("Monster_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_51 {
            get {
                object obj = ResourceManager.GetObject("Monster_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_52 {
            get {
                object obj = ResourceManager.GetObject("Monster_52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\great_sword.svg.
        /// </summary>
        internal static string monster_damage_cut {
            get {
                return ResourceManager.GetString("monster_damage_cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_dragon.svg.
        /// </summary>
        internal static string monster_damage_dragon {
            get {
                return ResourceManager.GetString("monster_damage_dragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_fire.svg.
        /// </summary>
        internal static string monster_damage_fire {
            get {
                return ResourceManager.GetString("monster_damage_fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_ice.svg.
        /// </summary>
        internal static string monster_damage_ice {
            get {
                return ResourceManager.GetString("monster_damage_ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\hammer.svg.
        /// </summary>
        internal static string monster_damage_impact {
            get {
                return ResourceManager.GetString("monster_damage_impact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Item\item_ammo.svg.
        /// </summary>
        internal static string monster_damage_shot {
            get {
                return ResourceManager.GetString("monster_damage_shot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_thunder.svg.
        /// </summary>
        internal static string monster_damage_thunder {
            get {
                return ResourceManager.GetString("monster_damage_thunder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_water.svg.
        /// </summary>
        internal static string monster_damage_water {
            get {
                return ResourceManager.GetString("monster_damage_water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_monster_kinsect.svg.
        /// </summary>
        internal static string monster_kinsect {
            get {
                return ResourceManager.GetString("monster_kinsect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_status_blast.svg.
        /// </summary>
        internal static string monster_weakness_blast {
            get {
                return ResourceManager.GetString("monster_weakness_blast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_dragon.svg.
        /// </summary>
        internal static string monster_weakness_dragon {
            get {
                return ResourceManager.GetString("monster_weakness_dragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_fire.svg.
        /// </summary>
        internal static string monster_weakness_fire {
            get {
                return ResourceManager.GetString("monster_weakness_fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_ice.svg.
        /// </summary>
        internal static string monster_weakness_ice {
            get {
                return ResourceManager.GetString("monster_weakness_ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_status_paralysis.svg.
        /// </summary>
        internal static string monster_weakness_paralysis {
            get {
                return ResourceManager.GetString("monster_weakness_paralysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_status_poison.svg.
        /// </summary>
        internal static string monster_weakness_poison {
            get {
                return ResourceManager.GetString("monster_weakness_poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_status_sleep.svg.
        /// </summary>
        internal static string monster_weakness_sleep {
            get {
                return ResourceManager.GetString("monster_weakness_sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_status_stun.svg.
        /// </summary>
        internal static string monster_weakness_stun {
            get {
                return ResourceManager.GetString("monster_weakness_stun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_thunder.svg.
        /// </summary>
        internal static string monster_weakness_thunder {
            get {
                return ResourceManager.GetString("monster_weakness_thunder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_water.svg.
        /// </summary>
        internal static string monster_weakness_water {
            get {
                return ResourceManager.GetString("monster_weakness_water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Armor\arm.svg.
        /// </summary>
        internal static string ui_arm {
            get {
                return ResourceManager.GetString("ui_arm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_armor_arm.svg.
        /// </summary>
        internal static string ui_armor_arms {
            get {
                return ResourceManager.GetString("ui_armor_arms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_armor_chest.svg.
        /// </summary>
        internal static string ui_armor_chest {
            get {
                return ResourceManager.GetString("ui_armor_chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_armor_head.svg.
        /// </summary>
        internal static string ui_armor_head {
            get {
                return ResourceManager.GetString("ui_armor_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_armor_leg.svg.
        /// </summary>
        internal static string ui_armor_legs {
            get {
                return ResourceManager.GetString("ui_armor_legs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_armor_skill.svg.
        /// </summary>
        internal static string ui_armor_skill {
            get {
                return ResourceManager.GetString("ui_armor_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_armor_waist.svg.
        /// </summary>
        internal static string ui_armor_waist {
            get {
                return ResourceManager.GetString("ui_armor_waist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Armor\armorset_empty.svg.
        /// </summary>
        internal static string ui_armorset_empty {
            get {
                return ResourceManager.GetString("ui_armorset_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_side_charm.svg.
        /// </summary>
        internal static string ui_charm {
            get {
                return ResourceManager.GetString("ui_charm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Armor\chest.svg.
        /// </summary>
        internal static string ui_chest {
            get {
                return ResourceManager.GetString("ui_chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_decoration_1.svg.
        /// </summary>
        internal static string ui_decoration_1 {
            get {
                return ResourceManager.GetString("ui_decoration_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_decoration_2.svg.
        /// </summary>
        internal static string ui_decoration_2 {
            get {
                return ResourceManager.GetString("ui_decoration_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_decoration_3.svg.
        /// </summary>
        internal static string ui_decoration_3 {
            get {
                return ResourceManager.GetString("ui_decoration_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_defense.svg.
        /// </summary>
        internal static string ui_defense {
            get {
                return ResourceManager.GetString("ui_defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_dragon.svg.
        /// </summary>
        internal static string ui_element_dragon {
            get {
                return ResourceManager.GetString("ui_element_dragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_fire.svg.
        /// </summary>
        internal static string ui_element_fire {
            get {
                return ResourceManager.GetString("ui_element_fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_ice.svg.
        /// </summary>
        internal static string ui_element_ice {
            get {
                return ResourceManager.GetString("ui_element_ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_thunder.svg.
        /// </summary>
        internal static string ui_element_thunder {
            get {
                return ResourceManager.GetString("ui_element_thunder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_water.svg.
        /// </summary>
        internal static string ui_element_water {
            get {
                return ResourceManager.GetString("ui_element_water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Armor\head.svg.
        /// </summary>
        internal static string ui_head {
            get {
                return ResourceManager.GetString("ui_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_item_ammo.svg.
        /// </summary>
        internal static string ui_item_ammo {
            get {
                return ResourceManager.GetString("ui_item_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui_item_background {
            get {
                object obj = ResourceManager.GetObject("ui_item_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_item_item.svg.
        /// </summary>
        internal static string ui_item_item {
            get {
                return ResourceManager.GetString("ui_item_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_item_material.svg.
        /// </summary>
        internal static string ui_item_material {
            get {
                return ResourceManager.GetString("ui_item_material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_item_misc.svg.
        /// </summary>
        internal static string ui_item_misc {
            get {
                return ResourceManager.GetString("ui_item_misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Armor\leg.svg.
        /// </summary>
        internal static string ui_leg {
            get {
                return ResourceManager.GetString("ui_leg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_research_points.svg.
        /// </summary>
        internal static string ui_research_points {
            get {
                return ResourceManager.GetString("ui_research_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_side_armor.svg.
        /// </summary>
        internal static string ui_side_armor {
            get {
                return ResourceManager.GetString("ui_side_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_side_armor_set.svg.
        /// </summary>
        internal static string ui_side_armor_set {
            get {
                return ResourceManager.GetString("ui_side_armor_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_side_charm.svg.
        /// </summary>
        internal static string ui_side_charm {
            get {
                return ResourceManager.GetString("ui_side_charm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_side_decoration.svg.
        /// </summary>
        internal static string ui_side_decoration {
            get {
                return ResourceManager.GetString("ui_side_decoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_side_item.svg.
        /// </summary>
        internal static string ui_side_item {
            get {
                return ResourceManager.GetString("ui_side_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_side_monster.svg.
        /// </summary>
        internal static string ui_side_monster {
            get {
                return ResourceManager.GetString("ui_side_monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_side_skill.svg.
        /// </summary>
        internal static string ui_side_skill {
            get {
                return ResourceManager.GetString("ui_side_skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_side_weapon.svg.
        /// </summary>
        internal static string ui_side_weapon {
            get {
                return ResourceManager.GetString("ui_side_weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_skill_empty.svg.
        /// </summary>
        internal static string ui_skill_empty {
            get {
                return ResourceManager.GetString("ui_skill_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_skill_filled.svg.
        /// </summary>
        internal static string ui_skill_filled {
            get {
                return ResourceManager.GetString("ui_skill_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_skill_left.svg.
        /// </summary>
        internal static string ui_skill_left {
            get {
                return ResourceManager.GetString("ui_skill_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_skill_right.svg.
        /// </summary>
        internal static string ui_skill_right {
            get {
                return ResourceManager.GetString("ui_skill_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_skill_space.svg.
        /// </summary>
        internal static string ui_skill_space {
            get {
                return ResourceManager.GetString("ui_skill_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_slot_0_empty.svg.
        /// </summary>
        internal static string ui_slot_empty_0 {
            get {
                return ResourceManager.GetString("ui_slot_empty_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_slot_1_empty.svg.
        /// </summary>
        internal static string ui_slot_empty_1 {
            get {
                return ResourceManager.GetString("ui_slot_empty_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_slot_2_empty.svg.
        /// </summary>
        internal static string ui_slot_empty_2 {
            get {
                return ResourceManager.GetString("ui_slot_empty_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_slot_3_empty.svg.
        /// </summary>
        internal static string ui_slot_empty_3 {
            get {
                return ResourceManager.GetString("ui_slot_empty_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Armor\waist.svg.
        /// </summary>
        internal static string ui_waist {
            get {
                return ResourceManager.GetString("ui_waist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_weakness_effect_star.svg.
        /// </summary>
        internal static string ui_weakness_effect_star {
            get {
                return ResourceManager.GetString("ui_weakness_effect_star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_weakness_no_effect_star.svg.
        /// </summary>
        internal static string ui_weakness_no_effect_star {
            get {
                return ResourceManager.GetString("ui_weakness_no_effect_star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_zenny.svg.
        /// </summary>
        internal static string ui_zenny {
            get {
                return ResourceManager.GetString("ui_zenny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap waist {
            get {
                object obj = ResourceManager.GetObject("waist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\weapon_affinity.svg.
        /// </summary>
        internal static string weapon_affinity {
            get {
                return ResourceManager.GetString("weapon_affinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\weapon_attack.svg.
        /// </summary>
        internal static string weapon_attack {
            get {
                return ResourceManager.GetString("weapon_attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\bow.svg.
        /// </summary>
        internal static string weapon_bow {
            get {
                return ResourceManager.GetString("weapon_bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\charge_blade.svg.
        /// </summary>
        internal static string weapon_charge_blade {
            get {
                return ResourceManager.GetString("weapon_charge_blade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\weapon_deviation.svg.
        /// </summary>
        internal static string weapon_deviation {
            get {
                return ResourceManager.GetString("weapon_deviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\dual_blades.svg.
        /// </summary>
        internal static string weapon_dual_blades {
            get {
                return ResourceManager.GetString("weapon_dual_blades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\weapon_elderseal.svg.
        /// </summary>
        internal static string weapon_elderseal {
            get {
                return ResourceManager.GetString("weapon_elderseal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\weapon_element.svg.
        /// </summary>
        internal static string weapon_element {
            get {
                return ResourceManager.GetString("weapon_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_status_blast.svg.
        /// </summary>
        internal static string weapon_element_blast {
            get {
                return ResourceManager.GetString("weapon_element_blast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_dragon.svg.
        /// </summary>
        internal static string weapon_element_dragon {
            get {
                return ResourceManager.GetString("weapon_element_dragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_fire.svg.
        /// </summary>
        internal static string weapon_element_fire {
            get {
                return ResourceManager.GetString("weapon_element_fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_ice.svg.
        /// </summary>
        internal static string weapon_element_ice {
            get {
                return ResourceManager.GetString("weapon_element_ice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_status_paralysis.svg.
        /// </summary>
        internal static string weapon_element_paralysis {
            get {
                return ResourceManager.GetString("weapon_element_paralysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_status_poison.svg.
        /// </summary>
        internal static string weapon_element_poison {
            get {
                return ResourceManager.GetString("weapon_element_poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_status_sleep.svg.
        /// </summary>
        internal static string weapon_element_sleep {
            get {
                return ResourceManager.GetString("weapon_element_sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_thunder.svg.
        /// </summary>
        internal static string weapon_element_thunder {
            get {
                return ResourceManager.GetString("weapon_element_thunder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\General\ui_element_water.svg.
        /// </summary>
        internal static string weapon_element_water {
            get {
                return ResourceManager.GetString("weapon_element_water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\great_sword.svg.
        /// </summary>
        internal static string weapon_great_sword {
            get {
                return ResourceManager.GetString("weapon_great_sword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\gunlance.svg.
        /// </summary>
        internal static string weapon_gunlance {
            get {
                return ResourceManager.GetString("weapon_gunlance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\hammer.svg.
        /// </summary>
        internal static string weapon_hammer {
            get {
                return ResourceManager.GetString("weapon_hammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\heavy_bowgun.svg.
        /// </summary>
        internal static string weapon_heavy_bowgun {
            get {
                return ResourceManager.GetString("weapon_heavy_bowgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\hunting_horn.svg.
        /// </summary>
        internal static string weapon_hunting_horn {
            get {
                return ResourceManager.GetString("weapon_hunting_horn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\insect_glaive.svg.
        /// </summary>
        internal static string weapon_insect_glaive {
            get {
                return ResourceManager.GetString("weapon_insect_glaive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\lance.svg.
        /// </summary>
        internal static string weapon_lance {
            get {
                return ResourceManager.GetString("weapon_lance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\light_bowgun.svg.
        /// </summary>
        internal static string weapon_light_bowgun {
            get {
                return ResourceManager.GetString("weapon_light_bowgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\longs_word.svg.
        /// </summary>
        internal static string weapon_long_sword {
            get {
                return ResourceManager.GetString("weapon_long_sword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\note_1.svg.
        /// </summary>
        internal static string weapon_note_1 {
            get {
                return ResourceManager.GetString("weapon_note_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\note_2.svg.
        /// </summary>
        internal static string weapon_note_2 {
            get {
                return ResourceManager.GetString("weapon_note_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\note_3.svg.
        /// </summary>
        internal static string weapon_note_3 {
            get {
                return ResourceManager.GetString("weapon_note_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\weapon_notes.svg.
        /// </summary>
        internal static string weapon_notes {
            get {
                return ResourceManager.GetString("weapon_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\weapon_whetstone.svg.
        /// </summary>
        internal static string weapon_sharpness {
            get {
                return ResourceManager.GetString("weapon_sharpness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\weapon_slots.svg.
        /// </summary>
        internal static string weapon_slots {
            get {
                return ResourceManager.GetString("weapon_slots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\weapon_special_ammo.svg.
        /// </summary>
        internal static string weapon_special_ammo {
            get {
                return ResourceManager.GetString("weapon_special_ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\switch_axe.svg.
        /// </summary>
        internal static string weapon_switch_axe {
            get {
                return ResourceManager.GetString("weapon_switch_axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Weapon\sword_and_shield.svg.
        /// </summary>
        internal static string weapon_sword_and_shield {
            get {
                return ResourceManager.GetString("weapon_sword_and_shield", resourceCulture);
            }
        }
    }
}
