//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonsterHunterWorld.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonsterHunterWorld.Properties.String", typeof(String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Ammo.
        /// </summary>
        internal static string AmmoArmorAmmo {
            get {
                return ResourceManager.GetString("AmmoArmorAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster Ammo 1.
        /// </summary>
        internal static string AmmoCluster1Ammo {
            get {
                return ResourceManager.GetString("AmmoCluster1Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster Ammo 2.
        /// </summary>
        internal static string AmmoCluster2Ammo {
            get {
                return ResourceManager.GetString("AmmoCluster2Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster Ammo 3.
        /// </summary>
        internal static string AmmoCluster3Ammo {
            get {
                return ResourceManager.GetString("AmmoCluster3Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demon Ammo.
        /// </summary>
        internal static string AmmoDemonAmmo {
            get {
                return ResourceManager.GetString("AmmoDemonAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string AmmoDeviationAverage {
            get {
                return ResourceManager.GetString("AmmoDeviationAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string AmmoDeviationHigh {
            get {
                return ResourceManager.GetString("AmmoDeviationHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string AmmoDeviationLow {
            get {
                return ResourceManager.GetString("AmmoDeviationLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string AmmoDeviationNone {
            get {
                return ResourceManager.GetString("AmmoDeviationNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon Ammo.
        /// </summary>
        internal static string AmmoDragonAmmo {
            get {
                return ResourceManager.GetString("AmmoDragonAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhaust Ammo 1.
        /// </summary>
        internal static string AmmoExhaust1Ammo {
            get {
                return ResourceManager.GetString("AmmoExhaust1Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhaust Ammo 2.
        /// </summary>
        internal static string AmmoExhaust2Ammo {
            get {
                return ResourceManager.GetString("AmmoExhaust2Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flaming Ammo.
        /// </summary>
        internal static string AmmoFlamingAmmo {
            get {
                return ResourceManager.GetString("AmmoFlamingAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Ammo.
        /// </summary>
        internal static string AmmoFreezeAmmo {
            get {
                return ResourceManager.GetString("AmmoFreezeAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Ammo 1.
        /// </summary>
        internal static string AmmoNormal1Ammo {
            get {
                return ResourceManager.GetString("AmmoNormal1Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Ammo 2.
        /// </summary>
        internal static string AmmoNormal2Ammo {
            get {
                return ResourceManager.GetString("AmmoNormal2Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Ammo 3.
        /// </summary>
        internal static string AmmoNormal3Ammo {
            get {
                return ResourceManager.GetString("AmmoNormal3Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paralysis Ammo 1.
        /// </summary>
        internal static string AmmoParalysis1Ammo {
            get {
                return ResourceManager.GetString("AmmoParalysis1Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paralysis Ammo 2.
        /// </summary>
        internal static string AmmoParalysis2Ammo {
            get {
                return ResourceManager.GetString("AmmoParalysis2Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierce Ammo 1.
        /// </summary>
        internal static string AmmoPierce1Ammo {
            get {
                return ResourceManager.GetString("AmmoPierce1Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierce Ammo 2.
        /// </summary>
        internal static string AmmoPierce2Ammo {
            get {
                return ResourceManager.GetString("AmmoPierce2Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierce Ammo 3.
        /// </summary>
        internal static string AmmoPierce3Ammo {
            get {
                return ResourceManager.GetString("AmmoPierce3Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison Ammo 1.
        /// </summary>
        internal static string AmmoPoison1Ammo {
            get {
                return ResourceManager.GetString("AmmoPoison1Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison Ammo 2.
        /// </summary>
        internal static string AmmoPoison2Ammo {
            get {
                return ResourceManager.GetString("AmmoPoison2Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string AmmoRapidFalse {
            get {
                return ResourceManager.GetString("AmmoRapidFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid.
        /// </summary>
        internal static string AmmoRapidTrue {
            get {
                return ResourceManager.GetString("AmmoRapidTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Reload.
        /// </summary>
        internal static string AmmoRecoilAutoReload {
            get {
                return ResourceManager.GetString("AmmoRecoilAutoReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoil+2.
        /// </summary>
        internal static string AmmoRecoilAverage {
            get {
                return ResourceManager.GetString("AmmoRecoilAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoil+3.
        /// </summary>
        internal static string AmmoRecoilHigh {
            get {
                return ResourceManager.GetString("AmmoRecoilHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoil+1.
        /// </summary>
        internal static string AmmoRecoilLow {
            get {
                return ResourceManager.GetString("AmmoRecoilLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recoil+4.
        /// </summary>
        internal static string AmmoRecoilVeryHigh {
            get {
                return ResourceManager.GetString("AmmoRecoilVeryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Ammo 1.
        /// </summary>
        internal static string AmmoRecover1Ammo {
            get {
                return ResourceManager.GetString("AmmoRecover1Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Ammo 2.
        /// </summary>
        internal static string AmmoRecover2Ammo {
            get {
                return ResourceManager.GetString("AmmoRecover2Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string AmmoReloadFast {
            get {
                return ResourceManager.GetString("AmmoReloadFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string AmmoReloadNormal {
            get {
                return ResourceManager.GetString("AmmoReloadNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        internal static string AmmoReloadSlow {
            get {
                return ResourceManager.GetString("AmmoReloadSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Slow.
        /// </summary>
        internal static string AmmoReloadVerySlow {
            get {
                return ResourceManager.GetString("AmmoReloadVerySlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep Ammo 1.
        /// </summary>
        internal static string AmmoSleep1Ammo {
            get {
                return ResourceManager.GetString("AmmoSleep1Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep Ammo 2.
        /// </summary>
        internal static string AmmoSleep2Ammo {
            get {
                return ResourceManager.GetString("AmmoSleep2Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slicing Ammo.
        /// </summary>
        internal static string AmmoSlicingAmmo {
            get {
                return ResourceManager.GetString("AmmoSlicingAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyvernblast.
        /// </summary>
        internal static string AmmoSpecialAmmoWyvernblast {
            get {
                return ResourceManager.GetString("AmmoSpecialAmmoWyvernblast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyvernheart.
        /// </summary>
        internal static string AmmoSpecialAmmoWyvernheart {
            get {
                return ResourceManager.GetString("AmmoSpecialAmmoWyvernheart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyvernsnipe.
        /// </summary>
        internal static string AmmoSpecialAmmoWyvernsnipe {
            get {
                return ResourceManager.GetString("AmmoSpecialAmmoWyvernsnipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread Ammo 1.
        /// </summary>
        internal static string AmmoSpread1Ammo {
            get {
                return ResourceManager.GetString("AmmoSpread1Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread Ammo 2.
        /// </summary>
        internal static string AmmoSpread2Ammo {
            get {
                return ResourceManager.GetString("AmmoSpread2Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread Ammo 3.
        /// </summary>
        internal static string AmmoSpread3Ammo {
            get {
                return ResourceManager.GetString("AmmoSpread3Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticky Ammo 1.
        /// </summary>
        internal static string AmmoSticky1Ammo {
            get {
                return ResourceManager.GetString("AmmoSticky1Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticky Ammo 2.
        /// </summary>
        internal static string AmmoSticky2Ammo {
            get {
                return ResourceManager.GetString("AmmoSticky2Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticky Ammo 3.
        /// </summary>
        internal static string AmmoSticky3Ammo {
            get {
                return ResourceManager.GetString("AmmoSticky3Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunder Ammo.
        /// </summary>
        internal static string AmmoThunderAmmo {
            get {
                return ResourceManager.GetString("AmmoThunderAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tranq Ammo.
        /// </summary>
        internal static string AmmoTranqAmmo {
            get {
                return ResourceManager.GetString("AmmoTranqAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Ammo.
        /// </summary>
        internal static string AmmoWaterAmmo {
            get {
                return ResourceManager.GetString("AmmoWaterAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyvern Ammo.
        /// </summary>
        internal static string AmmoWyvernAmmo {
            get {
                return ResourceManager.GetString("AmmoWyvernAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arms.
        /// </summary>
        internal static string ArmorArms {
            get {
                return ResourceManager.GetString("ArmorArms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest.
        /// </summary>
        internal static string ArmorChest {
            get {
                return ResourceManager.GetString("ArmorChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        internal static string ArmorHead {
            get {
                return ResourceManager.GetString("ArmorHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs.
        /// </summary>
        internal static string ArmorLegs {
            get {
                return ResourceManager.GetString("ArmorLegs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist.
        /// </summary>
        internal static string ArmorWaist {
            get {
                return ResourceManager.GetString("ArmorWaist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade From.
        /// </summary>
        internal static string CharmUpgradeFrom {
            get {
                return ResourceManager.GetString("CharmUpgradeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Rate.
        /// </summary>
        internal static string DecorationDropRate {
            get {
                return ResourceManager.GetString("DecorationDropRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        internal static string DecorationSkill {
            get {
                return ResourceManager.GetString("DecorationSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Rank.
        /// </summary>
        internal static string GeneralHighRank {
            get {
                return ResourceManager.GetString("GeneralHighRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string GeneralLevel {
            get {
                return ResourceManager.GetString("GeneralLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Rank.
        /// </summary>
        internal static string GeneraLowRank {
            get {
                return ResourceManager.GetString("GeneraLowRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarity.
        /// </summary>
        internal static string GeneralRarity {
            get {
                return ResourceManager.GetString("GeneralRarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Materials.
        /// </summary>
        internal static string GeneralRequiredMaterials {
            get {
                return ResourceManager.GetString("GeneralRequiredMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        internal static string GeneralSkill {
            get {
                return ResourceManager.GetString("GeneralSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot.
        /// </summary>
        internal static string GeneralSlot {
            get {
                return ResourceManager.GetString("GeneralSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Price.
        /// </summary>
        internal static string ItemBuyPrice {
            get {
                return ResourceManager.GetString("ItemBuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carry Limit.
        /// </summary>
        internal static string ItemCarryLimit {
            get {
                return ResourceManager.GetString("ItemCarryLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo.
        /// </summary>
        internal static string ItemCategoryAmmo {
            get {
                return ResourceManager.GetString("ItemCategoryAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string ItemCategoryItem {
            get {
                return ResourceManager.GetString("ItemCategoryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string ItemCategoryMaterial {
            get {
                return ResourceManager.GetString("ItemCategoryMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string ItemCategoryMisc {
            get {
                return ResourceManager.GetString("ItemCategoryMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtain.
        /// </summary>
        internal static string ItemObtain {
            get {
                return ResourceManager.GetString("ItemObtain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Price.
        /// </summary>
        internal static string ItemSellPrice {
            get {
                return ResourceManager.GetString("ItemSellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ailment.
        /// </summary>
        internal static string MonsterAilment {
            get {
                return ResourceManager.GetString("MonsterAilment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blastblight.
        /// </summary>
        internal static string MonsterAilmentBlastblight {
            get {
                return ResourceManager.GetString("MonsterAilmentBlastblight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bleed.
        /// </summary>
        internal static string MonsterAilmentBleed {
            get {
                return ResourceManager.GetString("MonsterAilmentBleed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defensedown.
        /// </summary>
        internal static string MonsterAilmentDefensedown {
            get {
                return ResourceManager.GetString("MonsterAilmentDefensedown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragonblight.
        /// </summary>
        internal static string MonsterAilmentDragonblight {
            get {
                return ResourceManager.GetString("MonsterAilmentDragonblight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effluvia.
        /// </summary>
        internal static string MonsterAilmentEffluvia {
            get {
                return ResourceManager.GetString("MonsterAilmentEffluvia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme.
        /// </summary>
        internal static string MonsterAilmentExtreme {
            get {
                return ResourceManager.GetString("MonsterAilmentExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireblight.
        /// </summary>
        internal static string MonsterAilmentFireblight {
            get {
                return ResourceManager.GetString("MonsterAilmentFireblight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iceblight.
        /// </summary>
        internal static string MonsterAilmentIceblight {
            get {
                return ResourceManager.GetString("MonsterAilmentIceblight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string MonsterAilmentLarge {
            get {
                return ResourceManager.GetString("MonsterAilmentLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mud.
        /// </summary>
        internal static string MonsterAilmentMud {
            get {
                return ResourceManager.GetString("MonsterAilmentMud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paralysis.
        /// </summary>
        internal static string MonsterAilmentParalysis {
            get {
                return ResourceManager.GetString("MonsterAilmentParalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poison.
        /// </summary>
        internal static string MonsterAilmentPoison {
            get {
                return ResourceManager.GetString("MonsterAilmentPoison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roar.
        /// </summary>
        internal static string MonsterAilmentRoar {
            get {
                return ResourceManager.GetString("MonsterAilmentRoar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        internal static string MonsterAilmentSleep {
            get {
                return ResourceManager.GetString("MonsterAilmentSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string MonsterAilmentSmall {
            get {
                return ResourceManager.GetString("MonsterAilmentSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stun.
        /// </summary>
        internal static string MonsterAilmentStun {
            get {
                return ResourceManager.GetString("MonsterAilmentStun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderblight.
        /// </summary>
        internal static string MonsterAilmentThunderblight {
            get {
                return ResourceManager.GetString("MonsterAilmentThunderblight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tremor.
        /// </summary>
        internal static string MonsterAilmentTremor {
            get {
                return ResourceManager.GetString("MonsterAilmentTremor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterblight.
        /// </summary>
        internal static string MonsterAilmentWaterblight {
            get {
                return ResourceManager.GetString("MonsterAilmentWaterblight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        internal static string MonsterAilmentWind {
            get {
                return ResourceManager.GetString("MonsterAilmentWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string MonsterAltNone {
            get {
                return ResourceManager.GetString("MonsterAltNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string MonsterDamage {
            get {
                return ResourceManager.GetString("MonsterDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HitZone.
        /// </summary>
        internal static string MonsterHitzone {
            get {
                return ResourceManager.GetString("MonsterHitzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtain.
        /// </summary>
        internal static string MonsterObtain {
            get {
                return ResourceManager.GetString("MonsterObtain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string MonsterSizeLarge {
            get {
                return ResourceManager.GetString("MonsterSizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string MonsterSizeSmall {
            get {
                return ResourceManager.GetString("MonsterSizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weakness.
        /// </summary>
        internal static string MonsterWeakness {
            get {
                return ResourceManager.GetString("MonsterWeakness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string SettingCancelButton {
            get {
                return ResourceManager.GetString("SettingCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language require restart application, do you want to restart now?.
        /// </summary>
        internal static string SettingConfirmText {
            get {
                return ResourceManager.GetString("SettingConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Required.
        /// </summary>
        internal static string SettingConfirmTitle {
            get {
                return ResourceManager.GetString("SettingConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingLanguage {
            get {
                return ResourceManager.GetString("SettingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string SettingOKButton {
            get {
                return ResourceManager.GetString("SettingOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string SettingTitle {
            get {
                return ResourceManager.GetString("SettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to show the Armor Set.
        /// </summary>
        internal static string ToolTipArmorDisplayArmorSet {
            get {
                return ResourceManager.GetString("ToolTipArmorDisplayArmorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Name (Require Armor).
        /// </summary>
        internal static string ToolTipArmorSetBonusSkill {
            get {
                return ResourceManager.GetString("ToolTipArmorSetBonusSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        internal static string ToolTipDefense {
            get {
                return ResourceManager.GetString("ToolTipDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense Base.
        /// </summary>
        internal static string ToolTipDefenseBase {
            get {
                return ResourceManager.GetString("ToolTipDefenseBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense Max.
        /// </summary>
        internal static string ToolTipDefenseMax {
            get {
                return ResourceManager.GetString("ToolTipDefenseMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon.
        /// </summary>
        internal static string ToolTipDragon {
            get {
                return ResourceManager.GetString("ToolTipDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        internal static string ToolTipFire {
            get {
                return ResourceManager.GetString("ToolTipFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice.
        /// </summary>
        internal static string ToolTipIce {
            get {
                return ResourceManager.GetString("ToolTipIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Event.
        /// </summary>
        internal static string ToolTipQuestEvent {
            get {
                return ResourceManager.GetString("ToolTipQuestEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunder.
        /// </summary>
        internal static string ToolTipThunder {
            get {
                return ResourceManager.GetString("ToolTipThunder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string ToolTipWater {
            get {
                return ResourceManager.GetString("ToolTipWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        internal static string UISideArmor {
            get {
                return ResourceManager.GetString("UISideArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Set.
        /// </summary>
        internal static string UISideArmorSet {
            get {
                return ResourceManager.GetString("UISideArmorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charm.
        /// </summary>
        internal static string UISideCharms {
            get {
                return ResourceManager.GetString("UISideCharms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration.
        /// </summary>
        internal static string UISideDecorations {
            get {
                return ResourceManager.GetString("UISideDecorations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string UISideHome {
            get {
                return ResourceManager.GetString("UISideHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string UISideItem {
            get {
                return ResourceManager.GetString("UISideItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster.
        /// </summary>
        internal static string UISideMonster {
            get {
                return ResourceManager.GetString("UISideMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        internal static string UISideSkill {
            get {
                return ResourceManager.GetString("UISideSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon.
        /// </summary>
        internal static string UISideWeapon {
            get {
                return ResourceManager.GetString("UISideWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affinity.
        /// </summary>
        internal static string WeaponAffinity {
            get {
                return ResourceManager.GetString("WeaponAffinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo.
        /// </summary>
        internal static string WeaponAmmoAmmo {
            get {
                return ResourceManager.GetString("WeaponAmmoAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        internal static string WeaponAmmoCapacity {
            get {
                return ResourceManager.GetString("WeaponAmmoCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string WeaponAmmoReload {
            get {
                return ResourceManager.GetString("WeaponAmmoReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShotType.
        /// </summary>
        internal static string WeaponAmmoShotType {
            get {
                return ResourceManager.GetString("WeaponAmmoShotType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        internal static string WeaponAttack {
            get {
                return ResourceManager.GetString("WeaponAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack(True).
        /// </summary>
        internal static string WeaponAttackTrue {
            get {
                return ResourceManager.GetString("WeaponAttackTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costings.
        /// </summary>
        internal static string WeaponBowCostings {
            get {
                return ResourceManager.GetString("WeaponBowCostings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Costing.
        /// </summary>
        internal static string WeaponBowCostingsClose {
            get {
                return ResourceManager.GetString("WeaponBowCostingsClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string WeaponCreate {
            get {
                return ResourceManager.GetString("WeaponCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        internal static string WeaponDefense {
            get {
                return ResourceManager.GetString("WeaponDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation.
        /// </summary>
        internal static string WeaponDeviation {
            get {
                return ResourceManager.GetString("WeaponDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elderseal.
        /// </summary>
        internal static string WeaponElderseal {
            get {
                return ResourceManager.GetString("WeaponElderseal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string WeaponElderSealAverage {
            get {
                return ResourceManager.GetString("WeaponElderSealAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string WeaponElderSealHigh {
            get {
                return ResourceManager.GetString("WeaponElderSealHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string WeaponElderSealLow {
            get {
                return ResourceManager.GetString("WeaponElderSealLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string WeaponElderSealNone {
            get {
                return ResourceManager.GetString("WeaponElderSealNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        internal static string WeaponElement {
            get {
                return ResourceManager.GetString("WeaponElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blast.
        /// </summary>
        internal static string WeaponElementBlast {
            get {
                return ResourceManager.GetString("WeaponElementBlast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragon.
        /// </summary>
        internal static string WeaponElementDragon {
            get {
                return ResourceManager.GetString("WeaponElementDragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire.
        /// </summary>
        internal static string WeaponElementFire {
            get {
                return ResourceManager.GetString("WeaponElementFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Element.
        /// </summary>
        internal static string WeaponElementHidden {
            get {
                return ResourceManager.GetString("WeaponElementHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice.
        /// </summary>
        internal static string WeaponElementIce {
            get {
                return ResourceManager.GetString("WeaponElementIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paralysis.
        /// </summary>
        internal static string WeaponElementParalysis {
            get {
                return ResourceManager.GetString("WeaponElementParalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posion.
        /// </summary>
        internal static string WeaponElementPoison {
            get {
                return ResourceManager.GetString("WeaponElementPoison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        internal static string WeaponElementSleep {
            get {
                return ResourceManager.GetString("WeaponElementSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunder.
        /// </summary>
        internal static string WeaponElementThunder {
            get {
                return ResourceManager.GetString("WeaponElementThunder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string WeaponElementWater {
            get {
                return ResourceManager.GetString("WeaponElementWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string WeaponMelodyDuration {
            get {
                return ResourceManager.GetString("WeaponMelodyDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string WeaponMelodyExtension {
            get {
                return ResourceManager.GetString("WeaponMelodyExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodies.
        /// </summary>
        internal static string WeaponMelodyMelodies {
            get {
                return ResourceManager.GetString("WeaponMelodyMelodies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string WeaponNotes {
            get {
                return ResourceManager.GetString("WeaponNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Materials.
        /// </summary>
        internal static string WeaponRequiredMaterials {
            get {
                return ResourceManager.GetString("WeaponRequiredMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpness.
        /// </summary>
        internal static string WeaponSharpness {
            get {
                return ResourceManager.GetString("WeaponSharpness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        internal static string WeaponSkill {
            get {
                return ResourceManager.GetString("WeaponSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slots.
        /// </summary>
        internal static string WeaponSlots {
            get {
                return ResourceManager.GetString("WeaponSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Ammo.
        /// </summary>
        internal static string WeaponSpecialAmmo {
            get {
                return ResourceManager.GetString("WeaponSpecialAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bow.
        /// </summary>
        internal static string WeaponTypeBow {
            get {
                return ResourceManager.GetString("WeaponTypeBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Blade.
        /// </summary>
        internal static string WeaponTypeChargeBlade {
            get {
                return ResourceManager.GetString("WeaponTypeChargeBlade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual Blades.
        /// </summary>
        internal static string WeaponTypeDualBlades {
            get {
                return ResourceManager.GetString("WeaponTypeDualBlades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Sword.
        /// </summary>
        internal static string WeaponTypeGreatSword {
            get {
                return ResourceManager.GetString("WeaponTypeGreatSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gunlance.
        /// </summary>
        internal static string WeaponTypeGunlance {
            get {
                return ResourceManager.GetString("WeaponTypeGunlance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hammer.
        /// </summary>
        internal static string WeaponTypeHammer {
            get {
                return ResourceManager.GetString("WeaponTypeHammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Bowgun.
        /// </summary>
        internal static string WeaponTypeHeavyBowgun {
            get {
                return ResourceManager.GetString("WeaponTypeHeavyBowgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunting Horn.
        /// </summary>
        internal static string WeaponTypeHuntingHorn {
            get {
                return ResourceManager.GetString("WeaponTypeHuntingHorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insect Glaive.
        /// </summary>
        internal static string WeaponTypeInsectGlaive {
            get {
                return ResourceManager.GetString("WeaponTypeInsectGlaive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lance.
        /// </summary>
        internal static string WeaponTypeLance {
            get {
                return ResourceManager.GetString("WeaponTypeLance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Bowgun.
        /// </summary>
        internal static string WeaponTypeLightBowgun {
            get {
                return ResourceManager.GetString("WeaponTypeLightBowgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Sword.
        /// </summary>
        internal static string WeaponTypeLongSword {
            get {
                return ResourceManager.GetString("WeaponTypeLongSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Axe.
        /// </summary>
        internal static string WeaponTypeSwitchAxe {
            get {
                return ResourceManager.GetString("WeaponTypeSwitchAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sword And Shield.
        /// </summary>
        internal static string WeaponTypeSwordAndShield {
            get {
                return ResourceManager.GetString("WeaponTypeSwordAndShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        internal static string WeaponUpgrade {
            get {
                return ResourceManager.GetString("WeaponUpgrade", resourceCulture);
            }
        }
    }
}
